AnimalShelter/Models/Animal.cs
using System.Collections.Generic;
using System;
namespace AnimalShelter.Models
{

  public class Animal
  {
    public int AnimalId {get; set;}
    public string Name {get;set;}
    public string Gender {get;set;}
    public string Breed {get;set;}
    public DateTime DateAdmitted {get;set;}
    //
    //public static List<Animal> ourAnimals = new List<Animal>{};

    
    //
    public string Type {get;set;} // not sure if it goes here or needs to be own class

    public Animal()
    {
      
    }
    public Animal(int animalId, string name, string gender, string breed, DateTime dateAdmitted, string type)
    {
      AnimalId = animalId;
      Name = name;
      Gender = gender;
      Breed = breed;
      DateAdmitted = dateAdmitted;
      Type = type;
      
      //
      //ourAnimals.Add(this);
      //
    }
    public static void FeedAllAnimals()
    {
      //this feeds all animals
    }
    public void FeedThisAnimal()
    {
      //this feeds this one animal
    }
      
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    // public DbSet<Category> Categories { get; set; }
     public DbSet<Animal> Animal { get; set; }
     public DbSet<Type> Type { get; set; }
    
    public AnimalShelterContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

AnimalShelter/Models/Type.cs
namespace AnimalShelter.Models
{
    public class Type
    {
        public int TypeId {get; set;}
        public string AnimalType {get; set;}
    }
}

AnimalShelter/Models/test.cs
using System;
namespace cars
{

  class car
  {
    public bool lightsOn;

    public car()
    {

    }
    public static void updateComputers()
    {
      //update
      return;
    }
    public void horn()
    {
      //sound horn
      return;
    }
    public void start()
    {
      //start the car
      return;
    }
  }

  class toyota : car
  {
      public toyota()
      {

      }
      new public void horn()
      {
        //play toyota horn
        return;
      }
  }

  class program
  {
    public static void main()
    {
      car c = new car();
      toyota t = new toyota();
      t.horn();
      t.start();
      t.lightsOn = true;
      toyota.updateComputers();
    }
    

    

  }










}

AnimalShelter/Controllers/AnimalsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Controllers
{
  //[HttpPost("/Animals")]
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;
    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Animal> x = _db.Animal.ToList();
     
      return View(x);
    }
    public ActionResult Create()//httpGet
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animal.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult SortByName() //httpGet
    {
      // select * from animal order by Name 
      List<Animal> model = _db.Animal.OrderBy(a => a.Name).ToList();
       


      // select * from animal where Type = Cat
      //List<Animal> model = _db.Animal.Where(a => a.Type == "Cat").ToList();


      return View("Index", model);
    }
    // public ActionResult Test() //httpGet
    // {
    //   List<Animal> model = _db.Animal.OrderBy(a => a.Name).ToList();

    //   List<Animal> our_Animals = Animal.ourAnimals;
    //   string b = Animal.Breed;
    //   Animal a = new Animal(1,"bob","male", "mutt", DateTime.Now, "dog");
      
    //   Animal.FeedAllAnimals(); // static meth
    //   //Animal.FeedThisAnimal(); error

    //   a.FeedThisAnimal(); // not static
    //  // a.FeedAllAnimals(); error
    //   return View("Index");
    // }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller
  {
    
    public ActionResult Index()
    {
      return View();
    }
  }
}

AnimalShelter/Controllers/TypesController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class TypesController : Controller
  {
    private readonly AnimalShelterContext _db;

    public TypesController(AnimalShelterContext db)
    {
      _db = db;
    }
   
    public ActionResult Index()
    {
      List<Type> model = _db.Type.ToList();
      return View(model);
    }
     public ActionResult Create() 
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Type type)
    {
        _db.Type.Add(type);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
// public ActionResult Details(int id)
// {
//     Item thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
//     return View(thisItem);
// }

  }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add a new Animal</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.LabelFor(model => model.Gender)
    @Html.TextBoxFor(model => model.Gender)
    @Html.LabelFor(model => model.Breed)
    @Html.TextBoxFor(model => model.Breed)
    @Html.LabelFor(model => model.DateAdmitted)
    @Html.EditorFor(model => model.DateAdmitted)
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
    <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}
@using AnimalShelter.Models;
<div class="container">
  @if(Model.Count == 0) 
  {
    <h1>There are no animals yet</h1>
  }
  <ul>
    
  @foreach (Animal a in Model)    
  {

      <li>@a.Name</li>
      <ul>
        <li>@a.Breed</li>
        <li>@a.Gender</li>
        <li>@a.DateAdmitted</li>
        <li>@a.Type</li>
      </ul>
  }
  </ul>
  <p>@Html.ActionLink("Add an Animal", "Create", "Animals")</p>
  <p>@Html.ActionLink("Sort by Name", "SortByName", "Animals")</p>
  <p>@Html.ActionLink("View unsorted", "Index", "Animals")</p>
  
  
</div>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  <h1>Welcome to the Animal Shelter</h1>
  <p>@Html.ActionLink("See all animals", "Index", "Animals")</p>
  <p>@Html.ActionLink("See all animal types", "Index", "Types")</p>
</div>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Animal Shelter</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    
  </body>
</html>

AnimalShelter/Views/Types/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Type

<h4>Add a new Animal type</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.AnimalType)
    @Html.TextBoxFor(model => model.AnimalType)
    <input type="submit" value="Add new animal type" />
}
@* <p>@Html.ActionLink("Show all animals", "Index")</p> *@

AnimalShelter/Views/Types/Index.cshtml
@{
  Layout = "_Layout";
}
@using AnimalShelter.Models;
<div class="container">
  @if(Model.Count == 0)
  {
    <h1>There are no animal types yet</h1>
  }
  @foreach (AnimalShelter.Models.Type t in Model)
  {
      <p>@t.AnimalType</p>
  }
  <p>@Html.ActionLink("Add an AnimalType", "Create", "Types")</p>
  <p>@Html.ActionLink("View/add Animals", "Index", "Animals")</p>
</div>